# ~/.config/hypr

windowrule = workspace 1, match:class vivaldi
windowrule = workspace 3, match:class vivaldi-app.notion.com__-Default
windowrule = workspace 4, match:class vivaldi-web.whatsapp.com__-Default
windowrule = workspace 4, match:class vivaldi-app.slack.com__client_-Default
windowrule = workspace 5, match:class Alacritty
windowrule = workspace 8, match:class Spotify

exec-once = [workspace 1 silent] vivaldi
exec-once = [workspace 8 silent] spotify
exec-once = [workspace 5 silent] alacritty -e tmux new-session -A -s Work 
